// Generates public/sitemap.xml from the same content file the router uses, so a
// new marketing page can never be live-but-missing from the sitemap (or listed
// in the sitemap but 404). Runs on every build via the `prebuild` npm script.
//
//   node scripts/generate-sitemap.mjs

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { ALL_MARKETING_PAGES } from '../src/content/marketingPages.js'
import { LEGAL_PAGES } from '../src/content/legalPages.js'
import { SITE_URL } from '../src/lib/seo.js'

const outFile = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'sitemap.xml')
const lastmod = new Date().toISOString().slice(0, 10)

// Priority signals relative importance within our own site only; it is a weak
// hint, so the values just mirror the funnel: home > pricing > clusters.
const entries = [
  { loc: '/', priority: '1.0', changefreq: 'weekly' },
  ...ALL_MARKETING_PAGES.map((page) => ({
    loc: `/${page.slug}`,
    priority: page.group === 'pricing' ? '0.9' : '0.8',
    changefreq: 'monthly',
  })),
  // Legal pages are indexable on purpose: a product that stores customer
  // records is expected to have them, and Google reads their presence as a
  // trust signal. Low priority — they are not what we want ranked.
  ...LEGAL_PAGES.map((page) => ({
    loc: `/${page.slug}`,
    priority: '0.3',
    changefreq: 'yearly',
  })),
]

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/generate-sitemap.mjs — do not edit by hand.
     Source of truth: src/content/marketingPages.js -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries
  .map(
    (entry) => `  <url>
    <loc>${SITE_URL}${entry.loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${entry.changefreq}</changefreq>
    <priority>${entry.priority}</priority>
  </url>`
  )
  .join('\n')}
</urlset>
`

writeFileSync(outFile, xml, 'utf8')
console.log(`sitemap.xml written with ${entries.length} URLs`)
